### ISSUE TITLE
replace std::optional<T*> to std::optional<std::reference_wrapper<T>>

### ISSUE THREAD

**Issue by zyfjeff** [alibaba/hessian2-codec#3]
At present, the Object has an interface that returns the type [std::optional<T*>](https://github.com/alibaba/hessian2-codec/blob/main/hessian2/object.hpp#L222). This return type is troublesome for the user. Is the returned pointer pointing to a valid address? In fact, the pointer here is always valid. This would not be a problem if the return type was `std::optional<std::reference_wrapper<T>>`.

**Comment by wbpcode** [comment]
I will try land it.

**Comment by zyfjeff** [comment]
close by #20
