### ISSUE TITLE
Unified naming convention

### ISSUE THREAD

**Issue by wbpcode** [alibaba/hessian2-codec#4]
In the project, there are currently three different naming convention for member functions: 
* camelCase: method of most of class.
* PascalCase: method of hessian2::Reader/hessian2::Writer such as ReadNbytes, ByteAvailable etc.
* snake_case: some method of hessian2::Object to_string, to_long etc. 

It would be nice if they could be unified.

**Comment by wbpcode** [comment]
I could use some spare time to get this done. But first we need to confirm our naming convention.

**Comment by zyfjeff** [comment]
Great, @wbpcode
We're going to follow the code style of Envoy, and I'm going to transfer the code style and format related tools from Envoy.
